#-------------------------------
#  Test1 - Github Actions
#-------------------------------

name: Test-GitHub-Actions
env:
  APPLICATION_NAME       : "Name-of-Application"
  DEPLOY_PACKAGE_NAME    : "Package-deploy-ver-${{ github.sha }}"


on:
  push:
    branches: 
      - main

jobs:
  my_testing:
    runs-on: ubuntu-latest
    
    steps:
    - name: Print Hello message
      run : echo "Hello World from Testing job"
    
    - name: Execute few commands
      run : |
        echo "Hello1"
        echo "Hello2"
        echo "Application name: ${{ env.APPLICATION_NAME }}"
  
  my_deploy:
    runs-on: ubuntu-latest
    needs: [my_testing]
    
    steps:
      - name: Print Hello message
        run : echo "Hello World from Deploy job"

      - name: Print Deployment package
        run : echo "Deploy package name is ${{ env.DEPLOY_PACKAGE_NAME }}"
      
